### ISSUE TITLE
no binary release for 1.1

### ISSUE THREAD

**Issue by zenorogue** [AtomicTorchStudio/AtomicTorch.SteamToEpicAchievementsConverter#1]
It seems you have only released the binary for 1.0 -- which does not import the icons from Steam.

Also I have found a bug in 1.0: with the following line in the VDF

```"english"	"Collect 25 Fulgurities, in Hardcore mode, without escaping from a discharge (\"That was close\")."```

it will think that "That" is a language.

**Comment by aienabled** [comment]
Hello!

Hmm, for some reason the binary build was removed from 1.1.

> it will think that "That" is a language.

Thank you for reporting the bug with escaped quotes not being treated properly.
Luckily, updating nuget lib `VdfConverter` to the latest version (1.0.3) resolved it.

I've uploaded 1.2 now with the fix, please try.

Regards!
